// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp-60ISsLVxernfkF3MjoCWj3upt-kp-g',
    appId: '1:950785167572:web:a76d7feca3468f91482b41',
    messagingSenderId: '950785167572',
    projectId: 'my-flutter-app-e482c',
    authDomain: 'my-flutter-app-e482c.firebaseapp.com',
    storageBucket: 'my-flutter-app-e482c.firebasestorage.app',
    measurementId: 'G-0WFG555PDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkjZCt5EY--bybiDuSQuC9_5ektn-6UQA',
    appId: '1:950785167572:android:8ad39aa6b3425a86482b41',
    messagingSenderId: '950785167572',
    projectId: 'my-flutter-app-e482c',
    storageBucket: 'my-flutter-app-e482c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARhcDsPYTi3W0pivOquu9nL0KfbjWRnD8',
    appId: '1:950785167572:ios:183edfcda40ee4fe482b41',
    messagingSenderId: '950785167572',
    projectId: 'my-flutter-app-e482c',
    storageBucket: 'my-flutter-app-e482c.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARhcDsPYTi3W0pivOquu9nL0KfbjWRnD8',
    appId: '1:950785167572:ios:183edfcda40ee4fe482b41',
    messagingSenderId: '950785167572',
    projectId: 'my-flutter-app-e482c',
    storageBucket: 'my-flutter-app-e482c.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp-60ISsLVxernfkF3MjoCWj3upt-kp-g',
    appId: '1:950785167572:web:f8674dca771a1317482b41',
    messagingSenderId: '950785167572',
    projectId: 'my-flutter-app-e482c',
    authDomain: 'my-flutter-app-e482c.firebaseapp.com',
    storageBucket: 'my-flutter-app-e482c.firebasestorage.app',
    measurementId: 'G-HVS1GM755C',
  );
}
